### ISSUE TITLE
"allowOutsideClick" not working when focus trap button is outside the viewport

### ISSUE THREAD

**Issue by lbineau** [focus-trap/focus-trap#102]
Hello I think I found an issue with `allowOutsideClick: () => true`
Here is a sample code to reproduce: https://codepen.io/lbineau/pen/zYYmPVL (first button is working, second is not)

**How to reproduce**
Set `allowOutsideClick: () => true` on the focus trap. Click on a button outside focusTrap when focused element is not in the viewport.

**Expected behavior**
User should be able to click outside buttons outside of the focusTrap area, at anytime.

**Actual behavior**
User is not able to click on buttons outside the focusTrap area. When the focused element of focusTrap does not appear in the viewport, the browser scrolls to the focused element inside focusTrap area.

Happens on Chrome Desktop Mac/Windows and mobile devices with Chrome/Samsung browsers

**Comment by stefcameron** [comment]
Closing issues older than 2020. Please LMK if this is still a problem.
