### ISSUE TITLE
Click in FocusTrap causes first item to focus, causing the view to scroll back to the top

### ISSUE THREAD

**Issue by chrxs** [focus-trap/focus-trap#104]
Hi, I wonder if you can help me

We have a Modal with FocusTrap, initially focus is set to the close button, which is what we're after.

But we're seeing an issue where, when ever the modal is clicked focus goes back to the close button, and as our Modal has scrollable content, causes the view to scroll back to the top.

I've narrowed it down to:
```js
// In case focus escapes the trap for some strange reason, pull it back in.
function checkFocusIn(e) {
  // In Firefox when you Tab out of an iframe the Document is briefly focused.
  if (container.contains(e.target) || e.target instanceof Document) {
    return;
  }
  e.stopImmediatePropagation();
  tryFocus(state.mostRecentlyFocusedNode || getInitialFocusNode()); //<----- Here
}
```

Can you explain the intention?
Is the entire function because of: "In case focus escapes the trap for some strange reason, pull it back in."

- Thanks
Chris

**Comment by DJLionheart** [comment]
I've been running into some issues with this as well. Apparently `element.focus()` has an optional  parameter that defaults to `{preventScroll: false}`. I would like to propose the ability to set change `preventScroll` to `true` in situations where you don't want the scroll to occur.

**Comment by gregkohn** [comment]
@DJLionheart awesome fix 🙏 

@davidtheclark Appreciate you merging that in and this package in general. Possible to get a new release that includes this commit? Thanks!

**Comment by TobyGWilliams** [comment]
Hi there,

We would also be grateful to see this released (and pushed out to focus-trap-react). 

Many thanks

**Comment by davidtheclark** [comment]
We need this new option (`preventScroll`) to be documented, then I can cut a release. @wldcordeiro want to follow through on that? Happy to give you npm release permission after this.

**Comment by wldcordeiro** [comment]
@davidtheclark Will do! Sorry been really swamped on some dev work but I'll get that documented.

**Comment by julesbou** [comment]
Hi guys, this option is very helpful, that's a great addition. Would it be possible to release it?

**Comment by jtomaszewski** [comment]
Docs added and ts typedef provided, I think it's good to release.

**Comment by julesbou** [comment]
Also please note this feature is not implemented in Safari yet.

**Comment by nicolethoen** [comment]
@davidtheclark any chance this could get released soon? Anything I can do to help it along?

**Comment by davidtheclark** [comment]
@nicolethoen If you'd like to maintain the project, I think that's what it needs: #85.

**Comment by Devil005** [comment]
Hello Community,

Any update on this preventScroll option being released in which version?

**Comment by stefcameron** [comment]
Catching up here... AFAICT, all the work related to this issue has been merged and long since published now. Closing. LMK if that's not the case.
