### ISSUE TITLE
Adjust types to allow `initialFocus: () => undefined`

### ISSUE THREAD

**Issue by FloEdelmann** [focus-trap/focus-trap#1060]
`initialFocus` can be `undefined`, in this case the first tabbable node will be focused. Also, we can pass a function returning an element. But we can't return undefined in that function (according to the types):

https://github.com/focus-trap/focus-trap/blob/94645ebfc34b8de6fbddc9ae5ea45127bd4ef90e/index.d.ts#L12

But according to the implementation, it actually works:

https://github.com/focus-trap/focus-trap/blob/94645ebfc34b8de6fbddc9ae5ea45127bd4ef90e/index.js#L270

https://github.com/focus-trap/focus-trap/blob/94645ebfc34b8de6fbddc9ae5ea45127bd4ef90e/index.js#L233-L267

So I suggest to adjust the types to allow `undefined` as a valid function return type.

**Comment by stefcameron** [comment]
@FloEdelmann You're correct! Setting the option to `undefined` or a function that returns `undefined` is specifically handled in `getInitialFocusNode()` so the docs and typings should reflect that. Thank you for bringing this to my attention.

I'll get this sorted shortly!

**Comment by stefcameron** [comment]
@FloEdelmann Please have a look at #1062 and LMK if the typings look good now.

**Comment by stefcameron** [comment]
Fix published in v7.5.3

**Comment by FloEdelmann** [comment]
Thanks!
