### ISSUE TITLE
Mac Voiceover tab keys

### ISSUE THREAD

**Issue by mathemagics** [focus-trap/focus-trap#112]
When using the MacOS Voiceover tool for navigating pages, focus trap does not trap the focus since Mac Voiceover uses `control + option + arrow key` for navigating pages. Could we add these key combination for navigation in
```
function isTabEvent(e) {
  return e.key === 'Tab' || e.keyCode === 9;
}
```

**Comment by mruzekw** [comment]
Screen readers have their own "tab order" so to speak. They don't obey focus traps by themselves unless the user is using the `TAB` key to navigate. So it's probably best to leave out any other keybindings for "TAB" and manage screenreader trapping by `aria-hidden` and variants.

**Comment by stefcameron** [comment]
Closing very old issues. There have been a lot of improvements to the library (and tabbable) since I took over in July 2020, and this may be fixed now. If it's still an issue with the current release, feel free to re-open.

**Comment by spacedawwwg** [comment]
This is still an issue in the current release

**Comment by stefcameron** [comment]
@spacedawwwg Thank you for letting me know! I have no experience with the macOS Voiceover tool. What would be a repro, and is what was requested in https://github.com/focus-trap/focus-trap/issues/112#issue-595480291 a good solution?

**Comment by spacedawwwg** [comment]
Sorry, It's actually an issue for iOS VoiceOver (tested by a full time assistive tech user)

The original comment @mathemagics could be a solution but what @mruzekw mentions could also be an issue (in that maybe there is no key binding to leverage in VoiceOver) I am personally unsure

Does this require a new issue @stefcameron ?

**Comment by stefcameron** [comment]
Since it's iOS and not macOS, a new issue would be good, even better would be a PR for that issue from someone who has a setup to repro this easily and test a solution. 🙂
