### ISSUE TITLE
Update npm package to include new preventScroll option

### ISSUE THREAD

**Issue by r0skar** [focus-trap/focus-trap#117]
Hi, I was checking out the documentation and saw that there is an option "preventScroll", which seems to be exactly what I need for my current task, but it seems that the npm package version 5.1.0 does not include it yet(?) I was just wondering if you plan a release soon or if we should just use this repository as a package source for now?

**Comment by Devil005** [comment]
Hello, 

Any idea when we can get this preventScroll functionality in the updated version?

**Comment by brtdv** [comment]
+1

**Comment by stefcameron** [comment]
Catching up to old issues. focus-trap has been updated many times now. This option should be available.
