### ISSUE TITLE
IsHidden() causes a forced reflow

### ISSUE THREAD

**Issue by MartinMalinda** [focus-trap/focus-trap#121]
<img width="488" alt="Screenshot 2020-08-10 at 20 14 13" src="https://user-images.githubusercontent.com/9468793/89816045-171a1380-db46-11ea-8386-16f9c1c9b69f.png">

There's probably something about the `getComputedStyle` that forces the browser to reflow, creating a performance bottleneck.
https://gist.github.com/paulirish/5d52fb081b3570c81e3a#calling-getcomputedstyle

I wonder if there could be an alternative?

https://developers.google.com/web/fundamentals/performance/rendering/avoid-large-complex-layouts-and-layout-thrashing?utm_source=devtools#avoid-forced-synchronous-layouts

**Comment by Slapbox** [comment]
@MartinMalinda browser and OS?

**Comment by pythe** [comment]
I'm experiencing the same issue and interested in investigating an optimization here.

I see this in Chrome 86 on MacOS 10.15.7, and in Edge 84 on Windows 10 (in a VM). In my case, an extremely large `document` exacerbates the problem: Each forced layout takes 600+ms. Removing the need for this recalculation would halve the execution time of my callback.

**Comment by stefcameron** [comment]
There are a few uses of `getComputedStyle()` over in [tabbable](https://github.com/focus-trap/tabbable/blob/master/src/index.js#L193-L202) that would need to be addressed as well. For those, I wonder if we could get away with just looking at the `style` attribute instead of using the function.

**Comment by stefcameron** [comment]
The next publish of this library will update tabbable to 5.2.0, which will give focus-trap the ability to pass the new `displayCheck` option down to tabbable, which could help mitigate this issue. However, this could open a can of worms for focus-trap as I noted in #362. Comments welcome.

**Comment by stefcameron** [comment]
Closing. I assume tabbable 5.2.0 options have solved this problem.
