### ISSUE TITLE
Demo link doesn't work

### ISSUE THREAD

**Issue by gondo** [focus-trap/focus-trap#122]
Seems like davidtheclark.github.io doesn't work anymore and therefore links linked from README and repo `About` section are broken.

**Comment by stefcameron** [comment]
@gondo Thanks for the heads-up. Yes, David is passing-on the reins to `tabbable`, `focus-trap`, and `focus-trap-react` to new maintainers. I'm actively maintaining `focus-trap-react` now, and helping out in `focus-trap`.

I'm thinking Netlify could be a solution for this going forward. I'm sure there's a way we could reconfigure the demos to auto-deploy on Netlify. Then we could create a `focus-trap` Netlify account and have it monitor this repo for changes and host the demos.

**Comment by stefcameron** [comment]
Should be working now. I figured out how to update the demo page. https://focus-trap.github.io/focus-trap/demo/
