### ISSUE TITLE
how do i focus typeahead search list 

### ISSUE THREAD

**Issue by moiezshaikh18** [focus-trap/focus-trap#1240]
![Screenshot 2024-08-16 at 6 47 55 PM](https://github.com/user-attachments/assets/2ebd5fee-d387-4596-84ca-6b87d6a19480)

Can someone please advise how to move focus from first item list to last Item list as its an overlay for search Input

**Comment by stefcameron** [comment]
@moiezshaikh18 Thanks for inquiring! Have you tried using using [multiple container nodes](https://focus-trap.github.io/focus-trap/#demo-multipleelements) (i.e. your two lists) when creating your focus trap?

**Comment by moiezshaikh18** [comment]
Actually, I tried multiple options don't have many examples on the web so thought to create doubt. Do you have any code snippet?

**Comment by stefcameron** [comment]
The code for all the focus-trap demos is located [here](https://github.com/focus-trap/focus-trap/tree/master/docs) in the repo. The code for the multiple container nodes demo I referenced earlier is [here](https://github.com/focus-trap/focus-trap/blob/master/docs/js/multiple-elements.js). Note there are 3 other "multiple elements" demos that might help as well.

**Comment by moiezshaikh18** [comment]
@stefcameron  I have tried using container now the issue is it focuses on the first item of the first list then <div> closes out and moves focus to the next element in near <searchInput>.

**Comment by moiezshaikh18** [comment]
import React, { useState } from "react";
import SearchOverlay from "./SearchOverlay";

const SearchComponent = () => {
  const [showOverlay, setShowOverlay] = useState(false);

  const handleSearchClick = () => {
    setShowOverlay(true); // Show overlay when search bar is clicked
  };

  const handleOverlayClose = () => {
    setShowOverlay(false); // Close overlay when necessary
  };

  return (
    <div>
      <input
        type="text"
        placeholder="Search for products & more"
        onFocus={handleSearchClick}
      />
      <SearchOverlay showOverlay={showOverlay} onClose={handleOverlayClose} />
    </div>
  );
};

export default SearchComponent;

**Comment by moiezshaikh18** [comment]
import FocusTrap from "focus-trap-react";
import React, { useEffect, useRef } from "react";

const SearchOverlay = ({ showOverlay, onClose }) => {
  const overlayRef = useRef(null);

  useEffect(() => {
    if (showOverlay && overlayRef.current) {
      overlayRef.current.focus();
    }
  }, [showOverlay]);

  if (!showOverlay) return null;

  return (
    <FocusTrap active={showOverlay}>
      <div
        ref={overlayRef}
        tabIndex="-1"
        role="dialog"
        aria-labelledby="search-overlay"
        className="overlay-container"
        onBlur={onClose} // To close overlay when focus is lost
      >
        <div>
          <h5>List 1</h5>
          <ul tabIndex={0}>
            <li>
              <button>One</button>
            </li>
            <li>
              <button>two</button>
            </li>
            <li>
              <button>three</button>
            </li>
            <li>
              <button>Fours</button>
            </li>
          </ul>
        </div>
        <div>
          <h5>List 2</h5>
          <ul>
            <li>
              <button>One</button>
            </li>
            <li>
              <button>two</button>
            </li>
            <li>
              <button>Three</button>
            </li>
            <li>
              <button>Four</button>
            </li>
            <li>
              <button>Five</button>
            </li>
          </ul>
        </div>
      </div>
    </FocusTrap>
  );
};

export default SearchOverlay;

**Comment by stefcameron** [comment]
@moiezshaikh18 I would, but I have to focus on personal priorities right now, I'm sorry. It might be weeks before I can really have a good look.

**Comment by stefcameron** [comment]
I'm going to close this issue due to inactivity. LMK if you decide to get back to it.
