### ISSUE TITLE
Does `Escape` need to be handled in the capture phase?

### ISSUE THREAD

**Issue by jcfranco** [focus-trap/focus-trap#1247]
Based on the [implementation notes](https://github.com/focus-trap/focus-trap/blob/master/index.js#L748-L767), I understand why `Tab` key presses need to be handled in the capture phase. However, does this same approach need to apply to `Escape`?

Currently, it seems impossible to ignore an `Escape` key event that should be handled and canceled (via `preventDefault()`) by a child of a focus-trapping component. For example, in an open, focused combobox inside a modal, `Escape` should close the combobox but not close the focus trap, which isn't possible due to event cancelation limitations in the child. Worth noting that these example components use the default target/bubbling phase. 

Do you think the event phase for `Escape` could be adjusted?

**Comment by stefcameron** [comment]
@jcfranco It's an interesting thought. I'm swamped with personal matters right now; I'll try to check this out in a week or two.

**Comment by jcfranco** [comment]
Sounds good. I'm happy to help if you think this is worth pursuing. ✨💪✨

Thanks for the quick reply and for this awesome library!

**Comment by stefcameron** [comment]
@jcfranco Thank you for offering to make a PR for it! That would be a big help. On the surface, it seems like something we should fix, so I'd welcome a PR. Please add one or two tests to validate it if possible. I may not get to reviewing your PR still for a couple of weeks, though, and there's no rush on this one.

**Comment by stefcameron** [comment]
Fix published in 7.6.0
