### ISSUE TITLE
onActivate question

### ISSUE THREAD

**Issue by ahsath** [focus-trap/focus-trap#1312]
hi, in the docs is explained that:

> onActivate {() => void}: A function that will be called before sending focus to the target element upon activation.

so if we do something like:

`onActivate: () => focusTrap.pause();`

should it sent the focus to the target element (tabbable/focusable node)? _which currently it does, and traps the focus_

maybe i am misunderstanding the concept behind this function but i though that by pausing it, the tabbable/focusable node should not receive focus, can you clarify please

**Comment by stefcameron** [comment]
@ahsath Thanks for asking. Admittedly, `onActivate()` is called when the trap gets activated, and the code is not expecting the trap to get paused half-way through its activation process.

I would suggest either not activating the trap until you're ready for it to be activated, focus get to trapped, and and the initial node in the trap to get focus; or using the `onPostActivate()` hook instead, if you really must pause the trap nearly as soon as it's activated.

**Comment by ahsath** [comment]
i see, thanks
