### ISSUE TITLE
Leverage Cypress to add coverage for all/future demos

### ISSUE THREAD

**Issue by stefcameron** [focus-trap/focus-trap#143]
Unit tests with JSDom aren't effective because JSDom doesn't fully support focus events. Cypress is much better suited.

The goal is to add Cypress E2E tests to cover each demo's expected functionality, and to add new demos as test cases to cover future API enhancements.

Run E2E testing at each `push` and `pull-request` on major browsers:

- [x] Chrome
cypress supported

- [x] Firefox
cypress supported
Having problem running on git action with error msg `Browser: 'firefox' was not found on your system or is not supported by Cypress`, see [cypress image open issue](https://github.com/cypress-io/cypress-docker-images/issues/363)

- [ ] Edge(chromium-based)
cypress supported

- [ ] Edge(EdgeHTML/pre-chromium/IE11?)
Not supported by cypress at this moment. See [cypress IE 11 support github issue](https://github.com/cypress-io/cypress/issues/6423)

- [ ] Safari
Not supported by cypress at this moment. See [cypress macOS Safari support github issue](https://github.com/cypress-io/cypress/issues/6422)

FYI, this is also what we do over on `focus-trap-react`: https://github.com/focus-trap/focus-trap-react/issues/104

**Comment by liunate** [comment]
I can help some cypress tests over the weekend, how about let me take these tests?

```javascript
  describe('demo: iene', () => {
    // TODO
  });

  describe('demo: ifc', () => {
    // TODO
  });

  describe('demo: ht', () => {
    // TODO
  });
```

**Comment by stefcameron** [comment]
@liunate Certainly! Please do. Much appreciated!

**Comment by stefcameron** [comment]
#166 adds official FireFox support to Cypress! 🎉

**Comment by stefcameron** [comment]
We seem to be doing pretty good with testing on Chrome and FF, and those seem to be the main ones that Cypress supports. Closing.
