### ISSUE TITLE
Request: add method like "destroy" to remove focusTrap instance

### ISSUE THREAD

**Issue by driskull** [focus-trap/focus-trap#225]
Request: add method like "destroy" to remove focusTrap instance without calling onDeactivate.

Use case:

I would like to be able to remove a focusTrap instance and its listeners without the onDeactivate being called.

In my VDOM, when a new modal node is created, I would like to first remove the existing focusTrap and create a new one in its place. However, the only way I can remove listeners and get rid of the instance now is by calling deactivate but the issue is that this also triggers the onDeactivate which I don't want to trigger.

**Comment by stefcameron** [comment]
That's an interesting use case! What is `onDeactivate()` doing that isn't good in this case?

Did you know that the [deactivate method](https://github.com/focus-trap/focus-trap#focustrapdeactivatedeactivateoptions) takes options, including an `onDeactivate` override? By default, `deactivate()` will call the `onDeactivate` option you specified when you _created_ the trap, but if you call `deactivate({ onDeactivate: null | false })`, it'll skip entirely.

**Comment by driskull** [comment]
Ok ill take that approach. thanks!

**Comment by stefcameron** [comment]
Great! My pleasure. In that case, I'll close this issue, but please feel free to circle back here if it doesn't work out.
