### ISSUE TITLE
using Array.prototype.findIndex which is not supported on IE

### ISSUE THREAD

**Issue by randypuro** [focus-trap/focus-trap#257]
Recent change started using this method:

https://github.com/focus-trap/focus-trap/blob/master/index.js#L262
https://github.com/focus-trap/focus-trap/blob/master/index.js#L276

**Comment by stefcameron** [comment]
Shoot. Thank you. That's a more recent API. I'll fix that ASAP.

**Comment by stefcameron** [comment]
Fixing with #258

**Comment by stefcameron** [comment]
@all-contributors add @randypuro for bug

**Comment by stefcameron** [comment]
Fixed in v6.2.3
