### ISSUE TITLE
clickOutsideDeactivates doen't work reliably with 1password

### ISSUE THREAD

**Issue by maciejmyslinski** [focus-trap/focus-trap#268]
![image](https://user-images.githubusercontent.com/11421186/102337826-4678db00-3f93-11eb-9231-d10224d6acd5.gif)

The modal closes when I click on 1password icon. Now, I know it's because 1password renders its icon outside modal DOM structure. The question is: can we somehow prevent this unwanted behavior? Or at the very least point out in the documentation that this is something that people should watch out for?

**Comment by stefcameron** [comment]
Interesting... How about using the `allowOutsideClick` option as a function instead of using the `clickOutsideDeactivates` option (let it default to `false`)? With `allowOutsideClick` as a function, you can decide when an outside click is permitted (i.e. only permit it on an element that controls the trap and is able to deactivate it).

**Comment by maciejmyslinski** [comment]
I ended up setting `allowOutsideClick` to `true` and attaching a click event listener to the `div` that centers the modal element on the screen so that when it's clicked, the modal closes.

I never thought setting `clickOutsideDeactivates` could have such an effect with password managers. My point is - at the very least let's inform people about such caveats and provide them a recipe on how to deal with such cases. If we could improve the API somehow in order to come up with an easy recipe – even better 👍

**Comment by stefcameron** [comment]
> I ended up setting `allowOutsideClick` to `true` and attaching a click event listener to the `div` that centers the modal element on the screen so that when it's clicked, the modal closes.

🎉 

> I never thought setting `clickOutsideDeactivates` could have such an effect with password managers. My point is - at the very least let's inform people about such caveats and provide them a recipe on how to deal with such cases. If we could improve the API somehow in order to come up with an easy recipe – even better 👍

Sure! Some relevant information could be added to the `clickOutsideDeactivates` option in the README, and it could mention exploring `allowOutsideClick` as an alternative.

I also filed #269 earlier in response to your issue here, which may help too with this and other scenarios.

**Comment by stefcameron** [comment]
FYI, I added some info about `clickOutsideDeactivates` to the README. 😄

**Comment by stefcameron** [comment]
FYI, in version 6.3.0 just published, `clickOutsideDeactivates` can now also be a function that returns a boolean. The function receives the `MouseEvent` that triggered the click.
