### ISSUE TITLE
Focus problem in Firefox

### ISSUE THREAD

**Issue by louisschandeler** [focus-trap/focus-trap#296]
Hello,

I am using focus-trap and this one does not work correctly on Firefox. The focus does not pass in several `<a>` tags (if you test the demo on firefox: https://focus-trap.github.io/focus-trap/demo/)

<img width="662" alt="Screenshot 2021-01-26 at 13 22 33" src="https://user-images.githubusercontent.com/6583764/105844566-b8543380-5fd9-11eb-81d2-7f1864d8b157.png">

In this screenshot, the focus just goes to the "with" link (not in "some" and "focusable")

Do you have any solution for this problem ?
Thanks in advance for your help,
Regards,
Louis

**Comment by stefcameron** [comment]
Hi, @louisschandeler, I see you closed this issue. I assume that means you figured it out. 😄 Feel free to reach out if you run into any other issues.

**Comment by aaroncodehub** [comment]
Hi , @stefcameron @louisschandeler ,

I have the same issue, can you share your solution for this case ?

I solved the problem by changing the system preferences. However, I don't think it is an ideal solution as the end user may not have such experience to do so.

![image](https://user-images.githubusercontent.com/71854919/153117740-cbc4e163-6036-4a81-a913-bc9fee7e7577.png)

**Comment by stefcameron** [comment]
@aaroncodehub Hi! Focus-trap completely relies on standard Tab and Shift+Tab key behavior of moving focus forward and backward, respectively, between all tabbable elements on the page. I'm not sure focus-trap could handle alternate tab behavior. Enabling that setting is something I've always had to do just in general, not only for focus-trap, on macOS.

Having used Windows for many years in the past, this is also standard Tab key behavior on that OS, albeit it doesn't require enabling a setting like macOS does (kind of silly, IMO, but that's up to Apple; probably some kind of legacy macOS thing from decades ago).

If you can think of another solution, please do let me know.

**Comment by aaroncodehub** [comment]
Hi @stefcameron ,

thanks for getting back to me.

I totally agree. but the issue is that only first "a" tag element is focusable and it will skip the rest in Firefox. there is a same issue for demo https://focus-trap.github.io/focus-trap-react/demo/ while testing in Firefox.

I haven't found any solution.

**Comment by louisschandeler** [comment]
Hello @aaroncodehub,
Can you do this on Firefox settings please : 
Type about:config in the Firefox address bar, and Enter.
Type tabfocus in the search at top of the page.
Set the value of the tabfocus to 7.
Is it ok for you ?
