### ISSUE TITLE
Not compatible with ES2015 / ES6 (import)

### ISSUE THREAD

**Issue by sam-s4s** [focus-trap/focus-trap#30]
Hmm, I would be great if you could use this package in ES2015 / ES6 land (ie. with Rollup).

Currently only seems to be able to be used with require(), which isn't compatible.

Needs to be able to be imported...

import x2js from 'x2js';
-or even-
import * as x2js from 'x2js';

Any chance of that happening? :)

Also typings? :D

**Comment by davidtheclark** [comment]
This seems like a major problem with Rollup, right? Is there really no way to easily consume CommonJS modules?

**Comment by sam-s4s** [comment]
Yeah, I can't get my head around it lol

It seems like they just don't care about anything that isn't an ES6 module... Makes me sad!

**Comment by davidtheclark** [comment]
@sam-s4s: how about https://github.com/rollup/rollup-plugin-commonjs? Found that recommendation in the docs.

**Comment by sam-s4s** [comment]
Yeah, using this already (for rxjs), however it still doesn't let you use require() :( Only import

**Comment by davidtheclark** [comment]
@sam-s4s: With that plugin I think you should be able to `import` modules that use CommonJS. If that doesn't work for you, sounds like you might need to seek help in that repo, rather than here.

**Comment by mkay581** [comment]
Hello, @davidtheclark I am running into this same issue which makes this package unusable for me unfortunately. I am using Lit without any build process. es6 imports/exports are now supported by browsers and it would help make this package consumable using polymer/lit if it supported es6 import/exports. I do this with my packages also to ensure interoperability.

**Comment by patrickk** [comment]
Running into this problem as well @mkay581, I ended up modifying both tabbable and focus-trap to use `export default` and it seems to work, but are there any plans to migrate over to es6 syntax in the future? @davidtheclark

**Comment by mkay581** [comment]
Yeah I'd strongly encourage supporting es6 imports/exports. More and more people are using them and they're growing to be a community-wide standard. It wouldn't take much to update this package to use it. @davidtheclark would you accept a PR to do this?

**Comment by juampi** [comment]
Any updates on this @davidtheclark ?

**Comment by davidtheclark** [comment]
If anybody would like to submit a PR with minimal changes that add a build script to address this — without any breaking changes for non-ES2015 users — I'd be open to taking a look.

**Comment by gertcuykens** [comment]
I am stuck too on this example https://jsbin.com/saqoyinufi/edit?html,console,output
ref: https://github.com/material-components/material-components-web/issues/4507

**Comment by gertcuykens** [comment]
@kfranqueiro suggested the following

> I believe it should be feasible for focus-trap and tabbable to continue to ship the existing CommonJS module while also shipping ES5 wrapped in an ES module under a different file path, then point to the new file via the module property in package.json (?module on unpkg seems to correctly follow this).

**Comment by stefcameron** [comment]
FYI, this is fixed in `focus-trap@6.0.0` which now provides an ESM build! 🎉
