### ISSUE TITLE
Add displayCheck option to pass down to tabbable

### ISSUE THREAD

**Issue by stefcameron** [focus-trap/focus-trap#362]
Surface the work done in https://github.com/focus-trap/tabbable/pull/286 up through focus-trap so that traps can take advantage of it.

**Comment by stefcameron** [comment]
This new option is published in `tabbable@5.2.0`

**Comment by stefcameron** [comment]
At first, I thought we'd just do this, but digging into this more, it's unclear how best to proceed because I'm unsure of the expectations. `displayCheck` was an enhancement in `tabbable` to make its process for determining which nodes are hidden be optionally (with the "non-zero-area" and "none" settings) configurable.

That's fine if you're using `tabbable` __directly__, but supporting that on `focus-trap` is very different because other than ensuring focus is "trapped" inside a given set of containers, and ensuring that using the tab key works as expected within the confines of the trapped containers, `focus-trap` aims to get out of the way and let the browser dictate the tabbing sequence, and where focus should move next (as I said, other than when you're on a boundary; that's when `focus-trap` kicks in).

So if we support `displayCheck` as an option and pass it down to `tabbable()` and `isFocusable()` calls that `focus-trap` uses under the hood, and if someone creates a trap with `displayCheck: "non-zero-area"`, and if that trap has a `<div tabindex="0" style="width: 0; height: 0"></div>`, what should happen _when the browser attempts to set focus to that node_ -- even though it's no longer part of the set of nodes returned from the `tabbable()` check?

The default behavior of the browser (Chrome, at least) is to allow tabbing and setting focus to a tabbable/focusable element _even if it has zero size_. But now the "non-zero-area" results in `tabbable` treating it as non-tabbable/focusable and ignoring it.

Should `focus-trap` when detect that this node is not part of what `tabbable()` decided should be tabbable, and therefore treat it as though is _outside_ the trap -- even though it's _inside_ the trap?

This feels like a dangerous road to go down to me, mainly because:
1. We end-up with nodes inside traps that shouldn't be tabbed to, which kind of breaks the "trap" idea; and
2. We now start relying on `tabbable` to fully determine what's tabbable and what the sequence is, instead of just testing boundaries and letting the browser do the rest

I'm thinking this option should remain `tabbable`-specific, and not used by `focus-trap`.

**Comment by stefcameron** [comment]
Thank you for your perspective.

Right now, whenever the Tab key is pressed, focus-trap checks the node that will be focused (as determined by the browser) to see if it's in one of the configured trapped containers. If it's not, then it pulls the focus back inside to the most recently-focused node.

We'd have to now start treating even a single node within a configured container as a potentially disallowed target, and move the focus to the node following the most recently-focused node in the set of nodes found by `tabbable()`.

I still would rather avoid getting in the way of the browser as much as possible, but such an implementation might work.

**Comment by DaviDevMod** [comment]
Thank you for the insights on the logic of the trap.

Could it work to just check if the node that will focused is contained within the root of the trap?

This would result in leaving focusables up to the browser, and "non-zero-area" would only be useful regarding performance (cause zero-area elements within the trap would still be considered focusable, as if display was "full").

However as per [this issue](https://github.com/focus-trap/tabbable/issues/592) I opened on *tabbable*, there's the possibility that "non-zero-area" will no longer be more performant than "full" and in that case the implementation I'm suggesting here would not make sense.

**Comment by stefcameron** [comment]
> Could it work to just check if the node that will be focused is contained within the root of the trap?

A trap doesn't have a root. It has multiple containers, and seeks to move focus from one to the other and back around again in tab direction.

> However as per https://github.com/focus-trap/tabbable/issues/592 I opened on tabbable, there's the possibility that "non-zero-area" will no longer be more performant than "full" and in that case the implementation I'm suggesting here would not make sense.

Right. Let's see how that plays out.

Dealing with "non zero area" in focus-trap would mean more active monitoring of where focus is going, and increasing how much focus-trap works against the browser's normal tab flow. Unless there's huge demand for this, I'd prefer not to go there. And we can't just provide the option and then not handle it and let side effects be side effects. I don't think the side effects will be expected, even if they're documented.

**Comment by stefcameron** [comment]
This was addressed in https://github.com/focus-trap/tabbable/pull/604 so closing.
