### ISSUE TITLE
Setting initailFocus to element with tabIndex=-1 breaks shift+tab

### ISSUE THREAD

**Issue by SKaplan01** [focus-trap/focus-trap#363]
When the initialFocus is used to set focus either on the container or on any element with tabIndex=-1 that comes before all other tabbable elements inside the focus trap, pressing shift+tab gets stuck on this initial element. 

Instead, I would expect shift+tab to move focus to the last focusable element inside the focus trap.

You can see this in the demo page under "initially focused container" (https://focus-trap.github.io/focus-trap/demo/)

**Current behavior**
1. Activate the trap --> focus moves to the container
2. press shift + tab --> the focus does not move from the container
2. Press tab and THEN shift + tab and the focus will move in the expected loop

**Expected behavior**
1. Activate the trap --> focus moves to the container
2. press shift + tab --> the focus should move to the "deactivate trap" button

**Comment by stefcameron** [comment]
Thank you for reporting this, @SKaplan01, I will check it out!

**Comment by stefcameron** [comment]
Indeed, this is a problem. Thanks for pointing to a place where I could see it happening.

**Comment by stefcameron** [comment]
#376 should fix this.

![initial-focus-fixed-20210417+1250](https://user-images.githubusercontent.com/2855350/115123043-ca15f900-9f80-11eb-9982-163113ad97d7.gif)

**Comment by stefcameron** [comment]
Fixed in `focus-trap@6.4.0`. Enjoy!
