### ISSUE TITLE
Conditionally return focus

### ISSUE THREAD

**Issue by adamchipperfield** [focus-trap/focus-trap#481]
I'm looking to conditionally return focus to the previously focused element. For example, I want to check if the intended element is actually focusable (i.e. it may have disappeared by this point). Have checked out `checkCanReturnFocus` but can't seem to get this to work (docs are a bit vague for this option).

Can anyone help out here?

**Comment by stefcameron** [comment]
Hi, @adamchipperfield,

`checkCanReturnFocus` only _delays_ the return of the focus. I don't think that's what you want.

There's a `setReturnFocus` option, which you can set to a function, so you could change _where_ focus returns to, depending on some condition, when the trap is deactivated, but the function must return a node. So you can't choose _not_ to return focus somewhere.

The `trap.deactivate()` method, however, takes a `returnFocus` flag, which you can set to false to prevent focus from being returned anywhere. The only catch here is that your code needs to be the thing that calls the method (so that you could check if you want to return focus and then set this option as either true/false), not the library.

That means you'd have to disable options such as `escapeDeactivates` and `clickOutsideDeactivates` (might be the only two) to prevent focus-trap from auto-deactivating the trap under certain conditions you don't control (where the deactivate() method is called automatically).

**Comment by adamchipperfield** [comment]
Ah thanks for clearing that up, @stefcameron. Is there a way I'm able to take in the intended element, check it (i.e. see if it's visible) and then make a decision about if it should recieve focus?

I'll always return an element whatever happens, but I need to basically vet the element focus-trap is going to focus back to.

**Comment by adamchipperfield** [comment]
Something like this:

```
setReturnFocus(element) {
  const parentDrawer = element.closest('.drawer')

  if (parentDrawer && parentDrawer.classList.contains('is-active')) {
    return element
  }

  return document.body
}
```

**Comment by stefcameron** [comment]
> Something like this:
> 
> ```
> setReturnFocus(element) {
>   const parentDrawer = element.closest('.drawer')
> 
>   if (parentDrawer && parentDrawer.classList.contains('is-active')) {
>     return element
>   }
> 
>   return document.body
> }
> ```
> 
> `element` being the one that focus-trap will set focus on by default.

My pleasure! This example is what you should be able to do (and what the `setReturnFocus` option is intended for) -- except for the part where you're expecting to get the element that focus-trap will set focus to if you don't return something else.

By default, that's the last element to have focus _before_ the trap is activated. That might be easy for you to determine, though, if you have one trigger, like a button, that activates the trap.

**Comment by adamchipperfield** [comment]
Gotcha, thanks! Here's my final solution:

- Opening a drawer will now take in an option to return focus to the body element
- If so, construct the focus trap with `setReturnFocus` returning `document.body`.

This way I'm just conditionally passing options as opposed to always having `setReturnFocus`:

```
createFocusTrap() {
  const options = {
    allowOutsideClick: true,
    escapeDeactivates: false
  }

  if (this.drawerObject) {
    if (this.drawerObject.returnFocusToBody) {
      options.setReturnFocus = () => document.body
    }
  }

  this.focusTrap = createFocusTrap(this.$refs.drawer, options)
}
```

Thanks for your help here, @stefcameron!

**Comment by stefcameron** [comment]
My, pleasure! Looks like a nice solution. All the best!

**Comment by Slapbox** [comment]
@stefcameron is there any way to use `setReturnFocus` or some other option to return focus UNLESS some condition is met? 

We'd like to allow focus trap to return focus to the previously focused element except in some cases - but there's nowhere we can tap into what element would be focused on deactivation - so it seems like we're forced to override it entirely or not at all. It would be great to have access to the previously focused element to use it in some deactivation/`setReturnFocus` logic.

**Comment by far-fetched** [comment]
Hey @Slapbox I had similar problem. I think everything what you need is indeed `setReturnFocus`. First argument provided to this callback is previously focused element (element focused before activation of focus trap). [Check example](https://github.com/focus-trap/focus-trap/blob/master/docs/js/set-return-focus-function.js#L10) IMO it is exactly what you talk about.

**Comment by Slapbox** [comment]
Ah I think you're right @far-fetched! Thanks for the reply. There's so much in the line on `setReturnFocus` that I didn't realize that one of the types it can accept is a function.

**Comment by Slapbox** [comment]
@far-fetched unfortunately `return false` inside of `setReturnFocus` leads to the error: "**`setReturnFocus` did not return a node**" and the `previousActiveElement` is `undefined` when trying to use this with `focus-trap-react`.

Any ideas? I'll also post on [focus-trap-react](https://github.com/focus-trap/focus-trap-react).
