### ISSUE TITLE
clickOutsideDeactivates is not placing focus on an element when the target is an unfocusable descendant

### ISSUE THREAD

**Issue by enagy27** [focus-trap/focus-trap#488]
## Problem
The current behavior of `clickOutsideDeactivates` will only retain focus on the clicked external element provided that element itself is focusable.

For example, given the following HTML:
```html
<button type="button">
  hello <span>world</span>
</button>
```
Clicking on "hello" would work as expected, but clicking on "world" would instead return focus to the element which was focused before the trap was opened because `e.target` refers to the `span`, which is not focusable in and of itself.

The code which causes this, I believe, is this line which would require a change to `isFocusable` from `tabbable`:
https://github.com/focus-trap/focus-trap/blob/4bab1fc5f3c2fb7b3531e713fbdd06bfbda30da2/index.js#L262

## Proposal
There are a few ways I could think to handle this 🤔  I'm not sure which is most in-line with this library.
1. Modify `isFocusable` directly and for all cases. This feels like a major functional change with unintended side-effects.
2. Modify `isFocusable` directly but with an option for including ancestors in the search, which would switch from using `Element.prototype.matches` to `Element.prototype.closest`.
3. Create an entirely separate method such as `findClosestFocusableContainer`

My intuition is that adding a new function would be the most straight-forward approach.

**Comment by henrijs** [comment]
Another option is

```button > * {
  pointer-events: none;
}```

**Comment by stefcameron** [comment]
Closing very old issues. If it's still an issue with the current release, feel free to re-open.
