### ISSUE TITLE
escapeDeactivates function does not receive the event

### ISSUE THREAD

**Issue by catarinacepeda** [focus-trap/focus-trap#498]
The documentation states that `escapeDeactivates` can be a function with the signature `(e: KeyboardEvent) => boolean`, but the KeyboardEvent is not being passed into the function.

The problem seems to be in [this line of code](https://github.com/focus-trap/focus-trap/blob/v6.6.1/index.js#L400), it should call `valueOrHandler(config.escapeDeactivates, e)`

**Comment by stefcameron** [comment]
@catarinacepeda Thanks for reporting this! Yes, I believe that's exactly right. I'll get that fixed-up and queued for the next release.
