### ISSUE TITLE
createFocusTrap no longer accepts undefined createOptions argument.

### ISSUE THREAD

**Issue by timleslie** [focus-trap/focus-trap#525]
The docs indicate that the `createOptions` argument is optional

<img width="856" alt="Screen Shot 2021-09-27 at 9 37 12 am" src="https://user-images.githubusercontent.com/616382/134828126-86a72f08-4aab-4792-b721-43d0a98b40a2.png">

The changes in the PR https://github.com/focus-trap/focus-trap/pull/504 try to access the `document` attribute on this argument, which throws an exception if the argument is undefined

https://github.com/focus-trap/focus-trap/blob/master/index.js#L99

**Comment by stefcameron** [comment]
Shoot, yes, thank you for reporting this. I'll get a patch out for this ASAP.
