### ISSUE TITLE
deactivate too late causes error in console

### ISSUE THREAD

**Issue by gbkwiatt** [focus-trap/focus-trap#545]
I am having issue, when inside focus-trap, I have teleport for modals. 
I have flags to activate/deactivate focus-trap, but the earliest I can do is `beforeDestroy`  and that seems to late as focus-trap throws error. 
I've tried to have default container that's focusable, inside it but I guess for a split second there is nothing there and it throws error. 

At least would be nice to be able to suppress console error, is there any way to do it ? 

Other thing is I don't really get why there is nothing when teleport content is being removed
```html
<focus-trap :active="portalActive">
            <portal-target
                id="modalPortal"
                name="modalPortal"
                aria-modal="true"
                tag="span"
                tabindex="0"
                @change="handleUpdate"
            />
        </focus-trap>
```

and `portal-targe` always seem to be there but yet I get 
`vue.runtime.esm.js?2b0e:619 [Vue warn]: Error in callback for watcher "active": "Error: Your focus-trap must have at least one container with at least one tabbable node in it at all times"`

**Comment by stefcameron** [comment]
It's been a while... I assume you've figured something out. Closing.
