### ISSUE TITLE
Enhancement - preventScroll option for "returnFocusOnDeactivate"

### ISSUE THREAD

**Issue by Delicious-Bacon** [focus-trap/focus-trap#546]
I use `position: sticky` for my header and a button in my header opens the modal with `<focus-trap>`.

Everything works, but there's an unwanted side-effect:
If the body is scrolled down (not on position `top: 0`) when closing the modal, the body will scroll up.

This is because `returnFocusOnDeactivate` calls a `focus()` method to the button that initially opened the modal, and since the header's position is `sticky`, it thinks it needs to scroll to top.

Proposal:
Add `FocusOptions` for `returnFocusOnDeactivate` to be able to set `preventScroll: true` when returning focus on trap deactivation (`beforeTrapHTMLElement.focus(FocusOptions)`).
[MDN - HTMLElement.focus()](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/focus)

As far as I am aware, the current `preventScroll` option on `focus-trap` does the wanted thing, but it does it for the `initialFocus` in the trap, not the `returnFocusOnDeactivate`.

**Comment by stefcameron** [comment]
Thanks for the proposal and your interest in/use of focus-trap! I'm wondering, though, why this isn't already working...

First, `preventScroll` is only used in a [single place](https://github.com/focus-trap/focus-trap/blob/b58f5efddd0deb246826a88a9d31c41ab7b99029/index.js#L267) in the code, and that's in the `tryFocus()` function.

Second, `tryFocus()` is [called on deactivation](https://github.com/focus-trap/focus-trap/blob/b58f5efddd0deb246826a88a9d31c41ab7b99029/index.js#L615), so `preventScroll` should be getting used on deactivation (as well as on activation).

Third, have you tried just setting `returnFocusOnDeactivate: false` in your focus-trap options? Or is it important to you that focus be returned after deactivation?

**Comment by Delicious-Bacon** [comment]
You are right, it should work.

I am using `vue-focus-trap` library which wraps on this library, but the Vue library does not pass all of the options to the `focus-trap`.

I'll close this issue and see it with the authors of the `vue-focus-trap`.

Thank you for your response! 💯

**Comment by stefcameron** [comment]
My pleasure!
