### ISSUE TITLE
Tab has no effect if tabindex=-1 element after other tabbable elements is focused

### ISSUE THREAD

**Issue by jpveooys** [focus-trap/focus-trap#565]
Hi,

If there is an element with tabindex=-1, it is focused, and it is the last element within the focus trap, pressing the tab key has no effect.

I've created a small demo here (with focus-trap 6.7.1):

https://codesandbox.io/s/focus-trap-tab-index-forked-gynbe

To reproduce:

1. Activate the trap
2. Use the mouse to focus the last button
3. Press the tab key

The focus doesn't move anywhere, while I would expect it to move back to the first button in the trap.

Shift+Tab isn't affected and tabs back as expected. Also, if the tabindex=-1 element isn't last, everything works as expected.

(Note: I'm finding codesandbox.io a bit temperamental – I've also put it on Netlify here as an alternative: https://csb-gynbe.netlify.app/)

# Demo

![focus-trap](https://user-images.githubusercontent.com/66470099/144857672-052a2c7e-4d77-4d85-ba40-956542c3109e.gif)

**Comment by stefcameron** [comment]
Thanks for reporting this, and for the repro (really helpful!). I'll check it out!

Possibly related (at least similar to) #375

**Comment by stefcameron** [comment]
@jpveooys I believe I have a fix for this: https://github.com/focus-trap/focus-trap/pull/588

**Comment by stefcameron** [comment]
@all-contributors add @jpveooys for bug
