### ISSUE TITLE
Clicking non-focusable elements within a trap causes the document.body to have focus

### ISSUE THREAD

**Issue by domarmstrong** [focus-trap/focus-trap#587]
Hi. I'm surprised I can't any other issues related to this. The issue can be seen in the demos. Clicking on any non-focusable elements inside a trap and then checking the `document.activeElement` will show the `document.body` has focus, so has effectively escaped the trap.

The problem I have is that the trap is used on a dialog, the dialog has stop propagation on all events as we don't want them to escape the dialog. The main application has some global event handlers for a few keys, which when the focus is within the dialog will not be triggered. However if the user clicks something non-focusable, the body gets focus and the global background event handlers can be triggered. I had worked around this by making the dialog have a tab index itself of -1, but that has yielded a problem itself where Chrome seems to stop text selection completely in elements with a tab index 🤷 .

Is there anything that I've missed that focus trap can do stop the body getting focus? Or is this something focus trap could/should handle?

I have another workaround, but its seems like a hack. In a timeout in a mouseup event handler on the body checking if the focus is still within any of the container elements and if not, returning it manually to the initial focus element in the dialog.

**Comment by stefcameron** [comment]
Hi, @domarmstrong!

> The issue can be seen in the demos. Clicking on any non-focusable elements inside a trap and then checking the document.activeElement will show the document.body has focus, so has effectively escaped the trap.

Upon closer inspection, I see that, yes. focus-trap _is_ monitoring clicks and focus changes on the document (to see all such events on any element it contains, to control focus), but when you click on a non-focusable element inside the trap, it looks at the `event.target` element, sees that it's inside the trap, and effectively does nothing. _Then_ I think the browser takes over and says, "hey, you clicked on nothing, but I need to focus _something_, so I'm going to focus the body." focus-trap doesn't appear to get a notification about that, however, so it remains unaware that focus has _technically_ escaped the trap.

> However if the user clicks something non-focusable, the body gets focus and the global background event handlers can be triggered.

If your app knows when a dialog is displayed, maybe you could disable those global key handlers?

> I had worked around this by making the dialog have a tab index itself of -1, but that has yielded a problem itself where Chrome seems to stop text selection completely in elements with a tab index 🤷 .

I tried making the div that defines the default focus-trap demo (first one at the top) have `tabindex="-1"`, but I didn't experience your selection issue:

![image](https://user-images.githubusercontent.com/2855350/148473602-8dda9ebf-91f4-4725-b96d-7b5670c4ee4c.png)

Maybe there's something else going on there?

**Comment by domarmstrong** [comment]
Thanks for taking a look.
Unfortunately disabling the other events would end up being messy due to legacy in the application.
Interesting that you don't see the selection issue, I will dig in to that a bit further to see if it's due to interaction with something else, as that would still be the simplest solution.

As you say you don't get any focus event when the body gains focus which makes this difficult to handle. Also when you click a `label` the body first gets focus before the related input is focused by the browser. So even if you did get a focus event on the body it could be incorrect.
I also tried handling via `focusout` events, you may get a `relatedTarget`, which is the element that will get focus which you could use to check if that is within the container elements. But then the issue with labels yields a `relatedTarget` of `null` even though the related input would be getting focus. Possibly the label case could be explicitly handled by looking up related input? I'll investigate that further if I have time.

**Comment by domarmstrong** [comment]
Digging in to the tabindex issue further I found the cause and now feel silly 😬 . The dialog container that was given the -1 tab index is actually outside the focus trap, so when you `mousedown` to start selection `focusin` fires on it and focus trap cancels the event, hence the text selection doesn't happen. Moving the tabindex -1 to the actual focus trapped element does fix it.

The focus can still escape to the body without this, but given that this is a simple solution to the problem I'll close the issue.

**Comment by stefcameron** [comment]
Thanks! I'm glad you found a simple solution to the problem. 😄
