### ISSUE TITLE
Update `clickOutsideDeactivates` on the fly

### ISSUE THREAD

**Issue by alexfedoseev** [focus-trap/focus-trap#67]
Use-case: modal w/ form can be hidden on click outside only if its fields are empty. Is it possible to update `clickOutsideDeactivates` setting w/o re-mounting the whole thing?

Thanks!

**Comment by davidtheclark** [comment]
It's not currently possible. However, deactivating a focus trap and creating a new one shouldn't be much work.

Since this would be an addition to the API, I'm hesitant to add it unless for some reason creating a new trap doesn't work.

**Comment by alexfedoseev** [comment]
@davidtheclark Sorry for the late response, just tried your suggestion and bumped into an issue: when I create focus trap for modal I provide `hideModal` function as `onDeactivate` hook and when I detect change of a value of `hideOnClickOutside` prop and trigger `deactivate` to reactivate focus trap w/ the new `clickOutsideDeactivates`, it hides a modal 😄

**Comment by davidtheclark** [comment]
I don't think I understand 😬

**Comment by alexfedoseev** [comment]
Sorry for confusion, I'll try to re-word. There's `Modal` component that has a `shown` bool prop. When it detects that this `prop` is switched from `false` to `true` it opens modal and activates focus trap as a side effect. Also, this component has `hide` prop—a function that hides `Modal`. Since focus trap has api to deactivate trap on `Esc` key and click outside, it's convinient to use `onDeactivate` hook to trigger `hide` handler on deactivation when `Esc` key is pressed or user clicks outside (basically, focus trap manages these scenarios for me). It works fine in general, but when I tried to re-mount focus trap w/ the new value of `clickOutsideDeactivates`, per suggestion, it triggered `onDeactivate` hook which closed modal.

**Comment by davidtheclark** [comment]
@alexfedoseev How about creating a new focus trap whenever the modal opens?

**Comment by stefcameron** [comment]
Closing issues older than 2020. Please LMK if this is still a problem.
