### ISSUE TITLE
Setting initialFocus=true leads to a call stack exceeded exception

### ISSUE THREAD

**Issue by stefcameron** [focus-trap/focus-trap#682]
Because we're not handling `true` as a possible value. Docs state that only `false` is supported, but code still needs to guard against `true` being given.

<img width="490" alt="image" src="https://user-images.githubusercontent.com/2855350/166310617-6fb06721-1a23-43d8-880c-e6ab195da694.png">

**Comment by far-fetched** [comment]
Hey @stefcameron
I can take care of this issue, if you don't mind.
How `trap` should behave when true is passed :thinking: Do we need any special handling or just throw an exception that this value is not supported ?

**Comment by stefcameron** [comment]
@far-fetched Thank you, I greatly appreciate that! I think we should interpret `true` as signaling that the user wants the default value, which is, "By default, when a focus trap is activated the first element in the focus trap's tab order will receive focus." That basically means ignoring `true` and doing what we would normally do if the option wasn't set at all.
