### ISSUE TITLE
The library is not working

### ISSUE THREAD

**Issue by SineYlo** [focus-trap/focus-trap#719]
I do everything according to the instructions, but for some reason it gives this error...
![image](https://user-images.githubusercontent.com/56423781/173511601-37e21199-9d85-4af4-b54e-32354b5c862b.png)

I also attach the JS code:
![image](https://user-images.githubusercontent.com/56423781/173511808-5ebe5d1b-9791-4cb2-b7f9-087d50e357ea.png)

And HTML markup:
![image](https://user-images.githubusercontent.com/56423781/173511912-d72ae54f-8515-47d8-b59f-08d03f8761e1.png)

Maybe I made a mistake after all?
To be honest, reading your documentation, not much is clear at all :D
Only code examples helped.

**Comment by SineYlo** [comment]
Thanks for the quick response!
In general, I did a little digging in the documentation and I managed to run this library :)
I attach the code that helped:
![image](https://user-images.githubusercontent.com/56423781/173521120-0b7374bd-5842-4335-8cee-c7802c8c06da.png)

**Comment by stefcameron** [comment]
@far-fetched Thanks for the hint! @SineYlo Glad you were able to figure it out.
