### ISSUE TITLE
No-refocus on first element when unpause called

### ISSUE THREAD

**Issue by justin-barca** [focus-trap/focus-trap#82]
The documentation states `Focus is forced into the trap just as described for focusTrap.activate().`  I have found this to not be the case.  Is the actual intent that the application will focus on the first tabbable element on unpause?  If so, I will create steps for reproduction.

**Comment by davidtheclark** [comment]
I don't think the intent has been to *focus* the first tabbable element in the unpaused trap, but just to trap focus once again. Maybe that sentence in the docs should be adjusted. Do you think there's a strong reason unpausing should always (or by default) focus the first tabbable element in the unpaused trap?

**Comment by stefcameron** [comment]
Closing issues older than 2020. Please LMK if this is still a problem.
