### ISSUE TITLE
Seeking co-maintainers!

### ISSUE THREAD

**Issue by davidtheclark** [focus-trap/focus-trap#85]
I've been shifting my focus away from UI development, so don't plan on addressing new issues myself. If you use this library and want to see development continue, you can make that happen by becoming a co-maintainer — with permissions to triage issues, merge PRs, cut releases, etc.

Please comment below if you're interested!

Another possibility is for a dedicated owner to fork this code and create a new package. I'd be happy to link to that library from the README of this one.

**Comment by theKashey** [comment]
What a pity. I've created my [focus-lock](https://github.com/theKashey/focus-lock) to provide some alternative to your one, and just recommended `focus-trap` as a solution for one issue, as long as behavior or your approach was better fitting their needs.

**Comment by jtomaszewski** [comment]
Still valid? Maybe I could help here.

**Comment by davidtheclark** [comment]
Sure, @jtomaszewski. I'll add you as a GH collaborator.

**Comment by jtomaszewski** [comment]
Would you be able to release a 5.0.1 ? ;]

**Comment by davidtheclark** [comment]
@jtomaszewski There was already a 5.0.1 published — not sure what was up with that — so I published 5.0.2.

**Comment by marksmccann** [comment]
@davidtheclark , @jtomaszewski Still looking for help? I am interested in collaborating.

**Comment by wldcordeiro** [comment]
🤚 @davidtheclark could I get collaborator here as well? Trying to do a synced update across the chain to `react-aria-modal` 😄

**Comment by petermakowski** [comment]
I'd be happy to help as well!

**Comment by haohello** [comment]
@davidtheclark I'm very curious to see if you have any roadmap of the possible features to rollout for this. That way, it might become easier for other interested people to know if they can lend in a hand.

**Comment by wldcordeiro** [comment]
I've got a few ideas for immediate work here and in `focus-trap-react` and `react-aria-modal`

* update dependencies in all (also my suggestion switch to `yarn`)
* add tests here using jest + testing-library/dom by converting examples
* update dependencies on `focus-trap` and `focus-trap-react` up the chain

**Comment by wldcordeiro** [comment]
@davidtheclark so I noticed something now that I'm trying to do maintaining. I'll need to be able to publish to npm for the packages (focus-trap, focus-trap-react, react-aria-modal, and react-displace) to get updates across the chain & clean up the react 16 warnings.

**Comment by davidtheclark** [comment]
@wldcordeiro 🆗 permissions are now assigned.

**Comment by UXDESIGNERLIN** [comment]
I'd like to co-maintain it :)

**Comment by nicolethoen** [comment]
@davidtheclark could you add @realredallen to your list of editors? He is on my team and could release the update.

**Comment by nicolethoen** [comment]
@davidtheclark could you add @realredallen to your list of editors? He is on my team and could release the update.

**Comment by davidtheclark** [comment]
@nicolethoen Looks like that's not a valid GitHub username.

**Comment by redallen** [comment]
Hi, I'm who @nicolethoen mentioned. My github is @redallen and my npm user is @realredallen.

I'm happy to be a co-maintainer.

**Comment by stefcameron** [comment]
@davidtheclark Given the inter-dependence of this library with `tabbable` and `focus-trap-react`, what do you think about moving this repo to the https://github.com/focus-trap org where we've already moved `focus-trap-react`? We have https://github.com/focus-trap/focus-trap-react/pull/87 now which I believe should really be a feature in `focus-trap`, and moving the repo there would allow me to address that. I'd still keep this issue open for maintainers, though!

**Comment by stefcameron** [comment]
@davidtheclark Thanks for moving the repo over!

**Comment by stefcameron** [comment]
@davidtheclark Did you happen to give @maraisr and myself NPM publish rights at the same time you moved the repo over? #120 will need publishing once merged, since we want to get that into `focus-trap-react`.

**Comment by stefcameron** [comment]
> @davidtheclark Did you happen to give @maraisr and myself NPM publish rights at the same time you moved the repo over? #120 will need publishing once merged, since we want to get that into `focus-trap-react`.

@davidtheclark Wondering about this ^^^

**Comment by davidtheclark** [comment]
@stefcameron Added you as a maintainer of both focus-trap and tabbable. I believe you can then add other c0-maintainers.

**Comment by stefcameron** [comment]
@davidtheclark Thank you!

**Comment by stefcameron** [comment]
Closing this. Seems like I'm running the show now. 😅
