### ISSUE TITLE
Can't focus other textfields while focusing on autocomplete

### ISSUE THREAD

**Issue by toduyen** [focus-trap/focus-trap#862]
**Describe the problem**: I am using MUI library to build my form interface. And using focus-trap to focus the textfields in the form and when focus comes to autocomplete, it can't focus anymore
**Video description**

https://user-images.githubusercontent.com/62172265/208568968-b9000363-a488-4564-bc15-3e578cdaf504.mp4

**Comment by stefcameron** [comment]
Hmmm, thanks for the recording. It looks like things are working fine as long as the autofocus element doesn't show up. But when it does, it looks like pressing `tab` from the autofocus element returns to the start of the trap (the first field at the top).

That could be an issue with focus-trap, or it could be an issue with MUI. I would need a repro in a sandbox somewhere, at the least, so I could debug it. Even better if you could debug it and see why focus is going back to that first field.

**Comment by stefcameron** [comment]
I will close this issue now. If you come up with a repro, I'll consider having another look.
