### ISSUE TITLE
`returnFocusOnDeactivate` not working on mobile.

### ISSUE THREAD

**Issue by vasiliki-b** [focus-trap/focus-trap#893]
On mobile, when `clickOutsideDeactivates` and `returnFocusOnDeactivate` are set to `true`, clicking on an outside focusable element will focus that element instead of returning focus to the initial element.

**Comment by stefcameron** [comment]
Does this also happen on desktop?

**Comment by stefcameron** [comment]
(And thank you for reporting this!)

**Comment by vasiliki-b** [comment]
It only happens on mobile (ie. through touch event).
(And no problem 🙂)

**Comment by stefcameron** [comment]
@vasiliki-b Looking further into this, it turns out it _is_ broken on desktop also. Not sure how you're seeing that it _isn't_.

In any case, thank you! 😄 I'll be fixing this shortly.

**Comment by stefcameron** [comment]
@all-contributors add @vasiliki-b for bug

**Comment by stefcameron** [comment]
Fixed in v7.3.0 just now.

**Comment by vasiliki-b** [comment]
Thanks for fixing this 🥳

**Comment by stefcameron** [comment]
@vasiliki-b You're welcome! 😄
