### ISSUE TITLE
Focus does seem to be working on firefox

### ISSUE THREAD

**Issue by ahsath** [focus-trap/focus-trap#895]
Go to the demo site and try tabbing through the demos, only one or two focus work

**Comment by stefcameron** [comment]
I tried a number of demos on https://focus-trap.github.io/focus-trap/ in FireFox macOS 108.0.2. They all work.

What version of FF are you using, and on what OS? Can you provide a recording of the behavior you're seeing?

**Comment by ahsath** [comment]
macOS Ventura 13.1
Firefox 109.0.1 - did not work
Safari 16.2 (18614.3.7.1.5) - did not work
Chrome 109.0.5414.119 - work

https://user-images.githubusercontent.com/37009121/219195813-d76d3da3-472a-4867-ace1-b61aaea1d367.mov

**Comment by stefcameron** [comment]
Hmm, OK, thanks for the info and the recording. The description you included for this issue indicated you were using the demo site, but that's not the case? That's what I looked at. Since you're using your own setup/code, can you give me a repro? Unless I can repro it, I can't try to fix it.

I'm on macOS Ventura 13.1 as well...

**Comment by ahsath** [comment]
Demo site
https://user-images.githubusercontent.com/37009121/219203164-3e538997-494e-4e32-a8e9-5de05463b42e.mp4

**Comment by stefcameron** [comment]
And for me (Chrome left, FF center, Safari right):

![ft-demos](https://user-images.githubusercontent.com/2855350/219206087-56bc2e83-ee89-437b-8979-2e0197488ac8.gif)

Chrome Version 109.0.5414.119
FF 109.0.1
Safari Version 16.2 (18614.3.7.1.5)

Do you perhaps not have this setting toggled on in your Keyboard settings?

<img width="460" alt="image" src="https://user-images.githubusercontent.com/2855350/219206818-fd3039d7-0b9c-4ac7-8026-4423bab7a6d7.png">

When I toggle that off, I get the same results you do...

**Comment by ahsath** [comment]
yes i had it toggled on, for some reason it wasn't working, i toggled it off and on again and started working but only on FF, safari still behaves as shown in the Demo site video
