### ISSUE TITLE
"default behavior" demo broken on Firefox

### ISSUE THREAD

**Issue by breville** [focus-trap/focus-trap#944]
The "default behavior" demo at https://focus-trap.github.io/focus-trap/ is broken on Firefox 112.0 on macOS 13.3.1.  Tabbing only moves between "with" and "deactivate trap".

**Comment by breville** [comment]
For what it's worth, [this article](https://css-tricks.com/proper-tabbing-to-interactive-elements-in-firefox-on-macos/) does have a macOS-level solution, which is to set `System Settings | Keyboard | Keyboard navigation` to "on".

**Comment by stefcameron** [comment]
<img width="646" alt="Screenshot 2023-04-14 at 6 23 37 PM" src="https://user-images.githubusercontent.com/2855350/232169912-df0cf0ac-9b43-48c1-9738-6fd9cbd0713d.png">

Hmmm, I have FF 112 on macOS 13.2.1 (bit older OS, but I doubt that would be the cause) and I can tab to all elements in the trap.

Did you first do as the big yellow warning says to do?

There's nothing focus-trap can do unless you set those settings. Without them, focus-trap would have to take complete control over the tab order, while focus-trap aims to let the browser determine order as much as possible. And focus-trap has no way of knowing if those OS settings are set or not.

**Comment by breville** [comment]
Sorry, I was just coming back to say that I saw the warning :)

**Comment by stefcameron** [comment]
Cool, thanks for closing the issue, and also for checking out focus-trap! 😄
