### ISSUE TITLE
Focus-trap inside iframe

### ISSUE THREAD

**Issue by MD4** [focus-trap/focus-trap#97]
**Context:**
 - Render DOM from the top window runtime inside an iframe
 - Then, activate the focus-trap on an rendered element

**Issue encountered:**
The referred document is the top window document and not the iframe inner document.

**Comment by stefcameron** [comment]
Closing issues older than 2020. Please LMK if this is still a problem.

**Comment by imvanzen** [comment]
> Closing issues older than 2020. Please LMK if this is still a problem.

I tested focus trap on iframe content and it is not working (https://focus-trap.github.io/focus-trap/#iframe)

**Comment by stefcameron** [comment]
@imvanzen What specifically is not working, and in what browser, and what OS?
