### ISSUE TITLE
focus-trap returns an error on Safari 15.3 and lower

### ISSUE THREAD

**Issue by msev** [focus-trap/focus-trap#996]
Hi,

Since 7.5.0, `focus-trap` is broken on Safari (macOS, iOS) on 15.3 and lower.

When I initialize `focus-trap`, the console returns the following error:

![focus-trap-findLast](https://github.com/focus-trap/focus-trap/assets/1529562/55117409-a77c-4d38-92a4-ddfeb49008f3)

I think it comes from [findLast()](https://caniuse.com/mdn-javascript_builtins_array_findlast), whose support is relatively recent.

Do you think you can fix this problem?

**Comment by stefcameron** [comment]
@msev Thank you. Very sorry about that. This will be fixed shortly. 

@DaviDevMod FYI...

**Comment by DaviDevMod** [comment]
Apologies, that was my bad.

I'm going to send a PR to fix it.

**Comment by msev** [comment]
Thanks @stefcameron and @DaviDevMod

**Comment by stefcameron** [comment]
@all-contributors add @msev for bug

**Comment by stefcameron** [comment]
The "with positive tab indexes" demo is one that uses the `findLast()` (and now our fix to that) and it runs without issue. Hopefully we've got our bases covered now.

**Comment by stefcameron** [comment]
Fix published in v7.5.2

**Comment by msev** [comment]
For your information, I've updated to version 7.5.2 and everything works well on Safari (13/14/15).

Thanks again for the patch!

**Comment by stefcameron** [comment]
Awesome! 😅 You're welcome.
